import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "getting-started" }],
  apikeysSidebar: [{ type: "autogenerated", dirName: "api-keys" }],
  developersSidebar: [{ type: "autogenerated", dirName: "developer-tools" }],
};

export default sidebars;
